# s3tupw1zard-pelican-wings configuration
name: pelican-wings

# Services section that specifies how the different services should be run
services:
  # This is the main app service for Pelican Wings
  app:
    # Name of the container
    container_name: pelican-wings

    # Docker image to use for the container
    image: ghcr.io/pelican-dev/wings:v1.0.0-beta7

    # Determines the restart policy. In this case, the container will always restart if it stops.
    restart: always

    # Maps the host's port 2022 to the container's port 2022
    ports:
      - "8080:8080"
      - "2022:2022"

    # Allocate a pseudo-TTY, making it act like a terminal
    tty: true

    # Set environment variables for the container
    environment:
      # Set the timezone to UTC
      TZ: "UTC"

      # Set the User ID for the Wings process
      WINGS_UID: 988

      # Set the Group ID for the Wings process
      WINGS_GID: 988

      # Set the username for the Wings process
      WINGS_USERNAME: pelican

    # Mount paths from the host into the container
    volumes:
      # Mount the Docker socket, allowing the container to communicate with the host's Docker daemon
      - "/var/run/docker.sock:/var/run/docker.sock"

      # Mount the Docker containers directory
      - "/var/lib/docker/containers:/var/lib/docker/containers"

      # Mount the configuration directory for Pelican
      - "/DATA/AppData/pelican-wings/etc:/etc/pelican"

      # Mount a temporary directory for Pelican
      - "/DATA/AppData/pelican-wings/tmp:/tmp/pelican/"

      # Mount the logs directory for Pelican
      - "/DATA/AppData/pelican-wings/logs:/var/log/pelican/"

      # Mount the logs directory for Pelican
      - "/var/log/pelican:/var/log/pelican/"

      # Mount the library directory for Pelican
      - "/DATA/AppData/pelican-wings/lib:/var/lib/pelican/"

      # Mount the letsencrypt directory for Pelican
      - "/etc/letsencrypt:/etc/letsencrypt"

    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: Timezone
        - container: WINGS_UID
          description:
            en_us: User ID for the Wings process
        - container: WINGS_GID
          description:
            en_us: Group ID for the Wings process
        - container: WINGS_USERNAME
          description:
            en_us: Username for the Wings process

      ports:
        - container: "8080"
          description:
            en_us: "The HTTP/HTTPS API Port" # Description for the port
        - container: "2022"
          description:
            en_us: "The SFTP Port" # Description for the port
      volumes:
        - container: /var/run/docker.sock
          description:
            en_us: Access to Docker socket # Description for Docker socket volume
        - container: /var/lib/docker/containers/
          description:
            en_us: Access the Docker containers # Description for Docker volumes volume
        - container: /tmp/pelican/
          description:
            en_us: Access to temporary directory # Description for Docker volumes volume
        - container: /etc/pelican/
          description:
            en_us: Access to configuration directory # Description for Docker volumes volume
        - container: /var/log/pelican/
          description:
            en_us: Access to logs directory # Description for Docker volumes volume
        - container: /var/lib/pelican/
          description:
            en_us: Access to library directory # Description for Docker volumes volume
        - container: /etc/letsencrypt
          description:
            en_us: Access to SSL certificates # Description for Docker volumes volume

# CasaOS specific configuration
x-casaos:
  architectures: # Supported CPU architectures
    - amd64
    - arm64
  main: app # Main service of the application
  description: # Description in different languages
    en_us: |
        Wings is Pelican's server control plane, built for the rapidly changing gaming industry and designed to be highly performant and secure. Wings provides an HTTP API allowing you to interface directly with running server instances, fetch server logs, generate backups, and control all aspects of the server lifecycle.

        In addition, Wings ships with a built-in SFTP server allowing your system to remain free of Pelican specific dependencies, and allowing users to authenticate with the same credentials they would normally use to access the Panel.
  tagline: # Short description or tagline in different languages
    en_us: Pelican Wings
  developer: "pelican-dev" # Developer's name or identifier
  author: s3tupw1zard # Author of this configuration
  icon: https://raw.githubusercontent.com/s3tupw1zard/CasaOS-AppStore/refs/heads/main/Apps/Pelican-Wings/pelican-icon.png
  # Thumbnail image (currently empty)
  thumbnail: ""
  # Title of the application in English
  title:
    en_us: Pelican Wings
  # Application category
  category: Games
  # Port mapping information
  port_map: "2022"
  tips:
    before_install:
      en_us: |
        Before setting up Pelican Wings in your container, you need to ensure that the node is properly configured in the Pelican panel. Follow these steps:

        Create the Node in the Pelican Panel: If you haven't already, initiate and configure the node within the Pelican panel.

        Copy the Configuration: After creating the node, the panel will provide a configuration file. You need to copy the content of this configuration and place it in:

        ```
        /DATA/AppData/pelican-wings/etc/config.yml
        ```

        Also make sure that you generate a ssl certificate for Wings to use. Therefore you could install certbot, since the path /etc/letsencrypt is mounted inside the container.

        This is only needed if you run Pelican Panel with a reverse proxy like Nginx Proxy Manager with a SSL certificate installed.

        Here you can find a how-to for installing certbot and issuing a new certificate:

        https://pelican.dev/docs/guides/ssl


        Tip: Use the CasaOS files app for an easy file management experience.

        Restart the Container: Once the configuration is in place, ensure you restart the container for the changes to take effect.